context:
  version: 3.4.0

package:
  name: lean-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/lean-language-server/-/lean-language-server-${{ version }}.tgz
  sha256: 0d53b0a075f3a03bf8333b26fdc0969d284ef6b47bb8ebcd97a298d05e5824d6

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "lean-language-server 2>&1 | grep -q \"Connection input stream is not set.\""

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Language server for Lean prover, version 3
  homepage: https://github.com/leanprover/lean-client-js
  repository: https://github.com/leanprover/lean-client-js

extra:
  recipe-maintainers:
    - danielnachun
